const classData = {
    furutaka: { name: 'Furutaka', type: 'Heavy Cruisers', ships: ['Furutaka', 'Kako'] },
    aoba: { name: 'Aoba', type: 'Heavy Cruisers', ships: ['Aoba', 'Kinugasa'] },
    myoko: { name: 'Myōkō', type: 'Heavy Cruisers', ships: ['Myōkō', 'Nachi', 'Ashigara', 'Haguro'] },
    takao: { name: 'Takao', type: 'Heavy Cruisers', ships: ['Takao', 'Atago', 'Chōkai', 'Maya'] },
    mogami: { name: 'Mogami', type: 'Heavy Cruisers', ships: ['Mogami', 'Mikuma', 'Suzuya', 'Kumano'] },
    tone: { name: 'Tone', type: 'Heavy Cruisers', ships: ['Tone', 'Chikuma'] },
    tenryu: { name: 'Tenryū', type: 'Light Cruisers', ships: ['Tenryū', 'Tatsuta'] },
    kuma: { name: 'Kuma', type: 'Light Cruisers', ships: ['Kuma', 'Tama', 'Kiso', 'Kitakami', 'Ōi'] },
    nagara: { name: 'Nagara', type: 'Light Cruisers', ships: ['Nagara', 'Natori', 'Kinu', 'Yura', 'Isuzu', 'Abukuma'] },
    sendai: { name: 'Sendai', type: 'Light Cruisers', ships: ['Sendai', 'Jintsū', 'Naka'] },
    yubari: { name: 'Yūbari', type: 'Light Cruisers', ships: ['Yūbari'] },
    katori: { name: 'Katori', type: 'Training Cruisers', ships: ['Katori', 'Kashima'] },
    agano: { name: 'Agano', type: 'Light Cruisers', ships: ['Agano', 'Yahagi', 'Sakawa'] },
    oyodo: { name: 'Ōyodo', type: 'Light Cruisers', ships: ['Ōyodo'] },
    'ning-hai': { name: 'Ning Hai', type: 'Light Cruisers', ships: ['Ioshima', 'Yasoshima'] },
    wakatake: { name: 'Wakatake', type: 'Destroyers', ships: ['Wakatake', 'Kuretake', 'Sanae', 'Yunagi', 'Namatake', 'Kaba', 'Tsubaki', 'Asagao'] },
    minekaze: { name: 'Minekaze', type: 'Destroyers', ships: ['Minekaze', 'Sawakaze', 'Okikaze', 'Shimakaze', 'Hakaze', 'Akikaze', 'Yakaze', 'Nadakaze', 'Hokaze', 'Tachikaze', 'Nokaze', 'Namikaze', 'Numakaze', 'Shiokaze', 'Yukaze'] },
    isokaze: { name: 'Isokaze', type: 'Destroyers', ships: ['Isokaze', 'Hamakaze', 'Amatsukaze', 'Tokitsukaze'] },
    kamikaze: { name: 'Kamikaze', type: 'Destroyers', ships: ['Kamikaze', 'Asakaze', 'Harukaze', 'Matsukaze', 'Hatakaze', 'Oite', 'Hayate', 'Asanagi', 'Yunagi'] },
    mutsuki: { name: 'Mutsuki', type: 'Destroyers', ships: ['Mutsuki', 'Kisaragi', 'Yayoi', 'Uzuki', 'Satsuki', 'Minazuki', 'Fumizuki', 'Nagatsuki', 'Kikuzuki', 'Mikazuki', 'Mochizuki', 'Yūzuki'] },
    fubuki: { name: 'Fubuki', type: 'Destroyers', ships: ['Fubuki', 'Shirayuki', 'Hatsuyuki', 'Miyuki', 'Murakumo', 'Shinonome', 'Usugumo', 'Shirakumo', 'Isonami', 'Uranami', 'Ayanami', 'Shikinami', 'Asagiri', 'Yūgiri', 'Akebono', 'Oboro', 'Sazanami', 'Ushio', 'Amagiri', 'Sagiri'] },
    hatsuharu: { name: 'Hatsuharu', type: 'Destroyers', ships: ['Hatsuharu', 'Nenohi', 'Wakaba', 'Hatsushimo', 'Ariake', 'Yūgure'] },
    akatsuki: { name: 'Akatsuki', type: 'Destroyers', ships: ['Akatsuki', 'Hibiki', 'Ikazuchi', 'Inazuma'] },
    shiratsuyu: { name: 'Shiratsuyu', type: 'Destroyers', ships: ['Shiratsuyu', 'Shigure', 'Murasame', 'Yūdachi', 'Harusame', 'Samidare', 'Yamakaze', 'Umikaze', 'Kawakaze', 'Suzukaze'] },
    akizuki: { name: 'Akizuki', type: 'Destroyers', ships: ['Akizuki', 'Teruzuki', 'Suzutsuki', 'Hatsuzuki', 'Niizuki', 'Wakatsuki', 'Shimotsuki', 'Fuyutsuki', 'Harutsuki', 'Yoizuki', 'Hanazuki', 'Natsuzuki'] },
    kagero: { name: 'Kagerō', type: 'Destroyers', ships: ['Kagerō', 'Shiranui', 'Kuroshio', 'Oyashio', 'Hayashio', 'Natsushio', 'Hatsukaze', 'Yukikaze', 'Amatsukaze', 'Tokitsukaze', 'Urakaze', 'Isokaze', 'Hamakaze', 'Tanikaze', 'Nowaki', 'Arashi', 'Hagikaze', 'Maikaze', 'Akigumo'] },
    asashio: { name: 'Asashio', type: 'Destroyers', ships: ['Asashio', 'Ōshio', 'Michishio', 'Arashio', 'Asagumo', 'Yamagumo', 'Natsugumo', 'Minegumo', 'Arare', 'Kasumi'] },
    yugumo: { name: 'Yūgumo', type: 'Destroyers', ships: ['Yūgumo', 'Makigumo', 'Kazagumo', 'Naganami', 'Makinami', 'Takanami', 'Ōnami', 'Kiyonami', 'Tamanami', 'Suzunami', 'Fujinami', 'Hayanami', 'Asashimo', 'Hayashimo', 'Akishimo', 'Kiyoshimo', 'Okinami', 'Kishinami', 'Yamanami'] },
    minegumo: { name: 'Minegumo', type: 'Destroyers', ships: ['Minegumo', 'Natsugumo', 'Asagumo'] },
    shimakaze: { name: 'Shimakaze', type: 'Destroyers', ships: ['Shimakaze'] }
};
